version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn discogportal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/discog/web/staticfiles/
      - media_volume:/home/discog/web/media/
    expose:
      - "8000"
    env_file:
      - ./env/sandbox/.env
    depends_on:
      - db
  db:
    image: timescale/timescaledb:1.6.1-pg11
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/sandbox/db/.env

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/discog/web/staticfiles/
      - media_volume:/home/discog/web/media/
    links:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
