# Generated by Django 3.0.5 on 2020-07-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_email', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('send_now', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_email', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('send_now', models.BooleanField(default=False)),
            ],
        ),
    ]
