# Generated by Django 3.0.5 on 2020-07-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discomail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailqueue',
            name='send_now',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email_server_response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email_status',
            field=models.CharField(choices=[('SUC', 'Success'), ('ERR', 'Error')], default='SUC', max_length=3),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('FPE', 'Forgot Password Email'), ('PJE', 'Platform Joining Email')], default='FPE', max_length=3),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='email_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_queues', to='discomail.EmailLog'),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='email_server_response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='email_status',
            field=models.CharField(choices=[('SUC', 'Success'), ('ERR', 'Error')], default='SUC', max_length=3),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='email_type',
            field=models.CharField(choices=[('FPE', 'Forgot Password Email'), ('PJE', 'Platform Joining Email')], default='FPE', max_length=3),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='from_email',
            field=models.CharField(default='testing@exiverprojects.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='from_email',
            field=models.CharField(default='testing@exiverprojects.com', max_length=255),
        ),
    ]
