# Generated by Django 3.0.5 on 2020-07-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discomail', '0002_auto_20200715_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='send_now',
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='email_queue',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_queues', to='discomail.EmailQueue'),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='send_now',
            field=models.BooleanField(default=False),
        ),
    ]
