# Generated by Django 3.0.5 on 2020-07-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discomail', '0003_auto_20200715_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='discomail.EmailQueue'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='from_email',
            field=models.CharField(default='discogsandbox@exiverprojects.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='from_email',
            field=models.CharField(default='discogsandbox@exiverprojects.com', max_length=255),
        ),
    ]
