# Generated by Django 3.0.5 on 2020-07-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discomail', '0004_auto_20200715_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='discomail.EmailQueue'),
        ),
    ]
