# Generated by Django 3.0.5 on 2020-07-18 22:53

import discoauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discomail', '0006_auto_20200718_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforminvite',
            name='invite_hash',
            field=models.CharField(default=discoauth.models.random_invite_hash, max_length=255),
        ),
    ]
