# Generated by Django 3.0.5 on 2020-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discomail', '0007_auto_20200718_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='from_email',
            field=models.CharField(default='disco-dev@exiverprojects.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='from_email',
            field=models.CharField(default='disco-dev@exiverprojects.com', max_length=255),
        ),
    ]
