# Generated by Django 3.0.5 on 2020-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discomail', '0008_auto_20200726_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='from_email',
            field=models.CharField(default='noreply@coding.discogacademy.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='from_email',
            field=models.CharField(default='noreply@coding.discogacademy.com', max_length=255),
        ),
    ]
