# Generated by Django 3.0.5 on 2020-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content_type',
            field=models.CharField(choices=[('TXT', 'RICH TEXT'), ('IMG', 'IMAGE'), ('TXT-IMG', 'TEXT AND IMAGE'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('QUIZ', 'QUIZ'), ('FILE', 'UPLOAD FILE - DOWNLOAD FILE'), ('INPUT-FIELD', 'INPUT FIELD')], default='TXT', max_length=30),
        ),
    ]
